export const EFFECT_METADATA = {
  faceSticker: {
    title: "PNG ステッカー貼り付け",
    shortLabel: "PNG ステッカー",
    category: "accessory",
    categoryLabel: "アクセサリ",
    badge: "Sticker",
    keywords: ["sticker", "png", "glasses", "accessory", "ステッカー", "アクセサリ"],
    requiredFeatures: ["Face"],
    description:
      "顔の目元を基準に PNG ステッカーを重ねる。画像素材を貼るタイプのエフェクトを足すときの土台。",
  },
  clownNose: {
    title: "ピエロの鼻",
    shortLabel: "ピエロ鼻",
    category: "accessory",
    categoryLabel: "アクセサリ",
    badge: "Face",
    keywords: ["clown", "nose", "red", "ピエロ", "鼻", "アクセサリ"],
    requiredFeatures: ["Face"],
    description: "鼻先ランドマークを基準に、赤い丸鼻を自然な影とハイライト付きで重ねる。",
  },
  sunglasses: {
    title: "サングラス",
    shortLabel: "サングラス",
    category: "accessory",
    categoryLabel: "アクセサリ",
    badge: "Face",
    keywords: ["sunglasses", "glasses", "eyes", "black", "サングラス", "メガネ", "アクセサリ"],
    requiredFeatures: ["Face"],
    description: "左右の目の位置と傾きに合わせて、黒いサングラスを顔へ重ねる。",
  },
  roundGlasses: {
    title: "丸眼鏡",
    shortLabel: "丸眼鏡",
    category: "accessory",
    categoryLabel: "アクセサリ",
    badge: "Glasses",
    keywords: ["round", "glasses", "frame", "丸眼鏡", "メガネ", "アクセサリ"],
    requiredFeatures: ["Face"],
    description: "左右の目と顔の傾きに追従する、透明レンズ付きの丸眼鏡。",
  },
  mustache: {
    title: "口ひげ",
    shortLabel: "口ひげ",
    category: "accessory",
    categoryLabel: "アクセサリ",
    badge: "Mustache",
    keywords: ["mustache", "moustache", "hair", "口ひげ", "ひげ", "アクセサリ"],
    requiredFeatures: ["Face"],
    description: "鼻先と口の位置を基準に、立体感のある口ひげを重ねる。",
  },
  crown: {
    title: "王冠",
    shortLabel: "王冠",
    category: "headwear",
    categoryLabel: "かぶり物",
    badge: "Crown",
    keywords: ["crown", "king", "queen", "gold", "王冠", "かぶり物"],
    requiredFeatures: ["Face"],
    description: "額の上に追従する、宝石と陰影付きの金色の王冠。",
  },
  partyHat: {
    title: "パーティーハット",
    shortLabel: "パーティー帽",
    category: "headwear",
    categoryLabel: "かぶり物",
    badge: "Party",
    keywords: ["party", "hat", "birthday", "パーティー", "帽子", "かぶり物"],
    requiredFeatures: ["Face"],
    description: "顔の位置と傾きに追従する、カラフルなパーティーハット。",
  },
  laserEyes: {
    title: "目からビーム",
    shortLabel: "目からビーム",
    category: "fun",
    categoryLabel: "おもしろ",
    badge: "Beam",
    keywords: ["laser", "beam", "eyes", "glow", "レーザー", "ビーム", "目", "おもしろ"],
    requiredFeatures: ["Face"],
    description: "両目から発光するビームを描き、光量をわずかに脈動させる。",
  },
  skinSoftening: {
    title: "肌補正",
    shortLabel: "肌補正",
    category: "beauty",
    categoryLabel: "補正",
    badge: "Skin",
    keywords: ["skin", "beauty", "smooth", "tone", "redness", "肌", "美肌", "補正", "赤み"],
    requiredFeatures: ["Face", "Segmentation"],
    description: "肌領域だけを自然に整える。目、眉、唇、鼻孔、髪、背景は補正対象から外す。",
  },
  squareHead: {
    title: "スクエア頭部変形",
    shortLabel: "スクエア頭部",
    category: "reshape",
    categoryLabel: "変形",
    badge: "Warp",
    keywords: ["square", "head", "warp", "reshape", "スクエア", "頭", "変形"],
    requiredFeatures: ["Face", "Segmentation"],
    description: "hair + face-skin の頭部マスクを使い、代表中心から左右へ四角く引き延ばす。",
  },
  triangleHead: {
    title: "三角頭部変形",
    shortLabel: "三角頭部",
    category: "reshape",
    categoryLabel: "変形",
    badge: "Warp",
    keywords: ["triangle", "head", "warp", "reshape", "三角", "頭", "変形"],
    requiredFeatures: ["Face", "Segmentation"],
    description: "hair + face-skin の頭部マスクを使い、上を広く下を細くして三角形に変形する。",
  },
};
